import React, { useState } from 'react';
import { 
  Sparkles, 
  TrendingUp, 
  Users, 
  ShieldAlert, 
  CheckCircle2, 
  DollarSign, 
  Target, 
  Rocket, 
  Compass, 
  Zap, 
  Layers, 
  BarChart3, 
  Star,
  ChevronRight,
  ArrowRight,
  Bot
} from 'lucide-react';
import { useLanguage } from '../../context/LanguageContext';

interface LandingPageProps {
  onStartValidation: () => void;
  onTryDemo: () => void;
  openAuthModal: (mode: 'login' | 'signup') => void;
}

export const LandingPage: React.FC<LandingPageProps> = ({ onStartValidation, onTryDemo, openAuthModal }) => {
  const { t } = useLanguage();
  const [billingCycle, setBillingCycle] = useState<'monthly' | 'annual'>('monthly');

  // Configurable Statistics
  const stats = [
    { label: 'Ideas Analyzed', value: '10K+', desc: 'Across 45+ startup industries' },
    { label: 'AI Validation Accuracy', value: '95%', desc: 'Empirical market signal match' },
    { label: 'Market Signals', value: '50+', desc: 'TAM, SAM, Competitor analysis' },
    { label: 'Availability', value: '24/7', desc: 'Real-time multi-LLM synthesis' }
  ];

  // Features list
  const features = [
    { icon: Sparkles, title: 'AI Idea Validation', desc: 'Get an instant 0-100 score dial and clear BUILD, VALIDATE, or PIVOT recommendation.' },
    { icon: TrendingUp, title: 'Market Research & TAM/SAM/SOM', desc: 'Automated addressable market sizing with growth rate and demand signals.' },
    { icon: Target, title: 'Competitor Intelligence', desc: 'In-depth matrix comparing strengths, weaknesses, pricing, and market positioning.' },
    { icon: DollarSign, title: 'Financial Analysis Calculator', desc: 'Interactive 1, 3, and 5-year revenue, CAC, LTV, break-even, and ROI projections.' },
    { icon: ShieldAlert, title: 'SWOT & Risk Assessment', desc: '2x2 SWOT matrix with probability, severity, and mitigation strategy grids.' },
    { icon: Users, title: 'Customer Discovery Personas', desc: 'Target customer demographic profiles with key pain points and motivations.' },
    { icon: Layers, title: 'MVP Feature Matrix', desc: 'Prioritized must-have, nice-to-have, and initially avoided feature lists.' },
    { icon: Rocket, title: 'Go-To-Market & Roadmap', desc: 'Multi-channel launch strategy and step-by-step development timeline.' },
    { icon: Bot, title: 'AI Business Coach', desc: 'Interactive AI advisor to answer specific questions about your saved idea.' }
  ];

  // How it works steps
  const steps = [
    { num: '01', title: 'Enter Your Business Idea', desc: 'Describe your concept, target market, expected pricing, and business model in a 5-step wizard.' },
    { num: '02', title: 'AI Researches & Synthesizes', desc: 'Multi-LLM algorithms evaluate market demand, unit economics, competition, and execution feasibility.' },
    { num: '03', title: 'Get Your Validation Score', desc: 'Receive a comprehensive 25+ page visual report with score dial, TAM charts, and financial models.' },
    { num: '04', title: 'Build With Confidence', desc: 'Use AI-generated MVP roadmaps, pitch decks, and marketing strategies to launch faster.' }
  ];

  // Testimonials
  const testimonials = [
    {
      name: 'Sarah Chen',
      role: 'Founder @ HealthPulse AI',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
      text: 'IdeaForge AI saved us months of wasted development by identifying a key competitor gap we overlooked. Our score of 88/100 gave investors immediate confidence during our seed round.',
      rating: 5
    },
    {
      name: 'David Miller',
      role: 'Serial Entrepreneur',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
      text: 'The financial calculator alone is worth 10x the price. Being able to project 5-year CAC and break-even points in 30 seconds changed how I validate early concepts.',
      rating: 5
    },
    {
      name: 'Priya Sharma',
      role: 'AgriTech Product Lead',
      image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
      text: 'The PDF reports generated by IdeaForge AI are stunning. I shared the shareable link with my co-founders and we immediately pivoted our business model based on the risk grid.',
      rating: 5
    }
  ];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 overflow-hidden">
      
      {/* Hero Section */}
      <section className="relative pt-20 pb-24 md:pt-28 md:pb-32 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[350px] bg-indigo-600/15 rounded-full blur-[140px] pointer-events-none"></div>

        <div className="text-center max-w-4xl mx-auto space-y-6">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/30 text-indigo-300 text-xs font-semibold tracking-wide backdrop-blur-md">
            <Sparkles className="w-3.5 h-3.5 text-indigo-400 animate-pulse" />
            <span>Next-Gen AI Business Validation Platform v1.0</span>
          </div>

          <h1 className="text-4xl sm:text-6xl font-extrabold text-white tracking-tight leading-[1.15]">
            Turn Your Business Idea Into a <span className="gradient-text">Data-Driven Decision.</span>
          </h1>

          <p className="text-base sm:text-lg text-slate-300 max-w-2xl mx-auto leading-relaxed">
            Validate your startup idea with AI-powered market research, competitor analysis, financial insights, risk assessment, and actionable growth strategies.
          </p>

          <div className="pt-4 flex flex-col sm:flex-row items-center justify-center gap-4">
            <button
              onClick={onStartValidation}
              className="w-full sm:w-auto px-8 py-4 rounded-xl text-base font-bold bg-indigo-600 hover:bg-indigo-500 text-white shadow-xl shadow-indigo-600/30 transition-all transform hover:-translate-y-0.5 flex items-center justify-center gap-2 group"
            >
              🚀 Validate My Idea
              <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </button>
            <button
              onClick={onTryDemo}
              className="w-full sm:w-auto px-8 py-4 rounded-xl text-base font-bold bg-slate-900 hover:bg-slate-800 text-slate-200 border border-slate-700/80 transition-all flex items-center justify-center gap-2"
            >
              📊 Explore Live Demo
            </button>
          </div>

          {/* Interactive UI Mockup Visualization */}
          <div className="pt-12 relative">
            <div className="relative rounded-2xl glass-card border border-slate-800 shadow-2xl overflow-hidden p-4 sm:p-6 bg-slate-900/90 backdrop-blur-xl">
              <div className="flex items-center justify-between pb-4 border-b border-slate-800/80">
                <div className="flex items-center space-x-2">
                  <div className="w-3 h-3 rounded-full bg-red-500/80"></div>
                  <div className="w-3 h-3 rounded-full bg-amber-500/80"></div>
                  <div className="w-3 h-3 rounded-full bg-emerald-500/80"></div>
                  <span className="text-xs text-slate-400 font-mono ml-2">ideaforge-ai.app/validation-analysis</span>
                </div>
                <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                  LIVE VALIDATION RESULT
                </span>
              </div>

              {/* Mockup Preview Grid */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-6 text-left">
                {/* Dial Score Mock */}
                <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 flex flex-col items-center justify-center text-center">
                  <div className="w-24 h-24 rounded-full border-4 border-indigo-500 flex flex-col items-center justify-center bg-indigo-500/10 shadow-lg shadow-indigo-500/20">
                    <span className="text-2xl font-extrabold text-white font-heading">84</span>
                    <span className="text-[9px] text-slate-400 font-semibold uppercase">/ 100 Score</span>
                  </div>
                  <span className="mt-3 px-3 py-1 rounded-full text-xs font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 flex items-center gap-1">
                    <CheckCircle2 className="w-3.5 h-3.5" /> 🟢 BUILD RECOMMENDATION
                  </span>
                </div>

                {/* Market Size TAM Mock */}
                <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-2">
                  <div className="flex items-center justify-between text-xs">
                    <span className="text-slate-400 font-semibold">Total Addressable Market</span>
                    <span className="text-indigo-400 font-mono font-bold">$18.5 Billion</span>
                  </div>
                  <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden">
                    <div className="bg-indigo-500 h-full w-[85%]"></div>
                  </div>
                  <p className="text-[11px] text-slate-400 pt-1">
                    Strong 14.2% CAGR demand growth in direct agricultural supply chain automation.
                  </p>
                </div>

                {/* Financial Break-even Mock */}
                <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 space-y-2">
                  <div className="flex items-center justify-between text-xs">
                    <span className="text-slate-400 font-semibold">Break-even Period</span>
                    <span className="text-emerald-400 font-mono font-bold">Month 7</span>
                  </div>
                  <div className="grid grid-cols-2 gap-2 text-xs pt-1">
                    <div className="p-2 rounded bg-slate-900 border border-slate-800">
                      <p className="text-[10px] text-slate-400">Year 1 Profit</p>
                      <p className="font-bold text-emerald-400">$80,000</p>
                    </div>
                    <div className="p-2 rounded bg-slate-900 border border-slate-800">
                      <p className="text-[10px] text-slate-400">5-Yr Revenue</p>
                      <p className="font-bold text-indigo-300">$3.4M</p>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
      </section>

      {/* Configurable Statistics Ticker */}
      <section className="py-12 border-y border-slate-900 bg-slate-900/40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            {stats.map((s, idx) => (
              <div key={idx} className="space-y-1">
                <p className="text-3xl sm:text-4xl font-extrabold text-white font-heading gradient-text">{s.value}</p>
                <p className="text-sm font-bold text-slate-200">{s.label}</p>
                <p className="text-xs text-slate-400">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Core Features Grid */}
      <section className="py-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-16 space-y-3">
          <h2 className="text-3xl font-extrabold text-white">Everything You Need To Validate & Launch</h2>
          <p className="text-slate-400 text-sm">
            Powered by multi-LLM intelligence engines to analyze your idea from every founder perspective.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {features.map((f, i) => {
            const IconComponent = f.icon;
            return (
              <div key={i} className="p-6 rounded-2xl glass-card border border-slate-800/80 hover:border-indigo-500/40 transition-all hover:-translate-y-1 group">
                <div className="w-12 h-12 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 mb-4 group-hover:scale-110 transition-transform">
                  <IconComponent className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-bold text-white mb-2">{f.title}</h3>
                <p className="text-xs text-slate-400 leading-relaxed">{f.desc}</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* 4-Step How It Works */}
      <section className="py-20 border-t border-slate-900 bg-slate-900/20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto mb-16 space-y-3">
            <h2 className="text-3xl font-extrabold text-white">How IdeaForge AI Works</h2>
            <p className="text-slate-400 text-sm">Four simple steps to transform raw concepts into investor-ready business plans.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 relative">
            {steps.map((step, idx) => (
              <div key={idx} className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 space-y-3 relative">
                <span className="text-3xl font-extrabold font-heading text-indigo-500/40">{step.num}</span>
                <h3 className="text-base font-bold text-white">{step.title}</h3>
                <p className="text-xs text-slate-400 leading-relaxed">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto mb-16 space-y-3">
          <h2 className="text-3xl font-extrabold text-white">Loved by Founders & Builders</h2>
          <p className="text-slate-400 text-sm">Join over 10,000 entrepreneurs validating their next big venture.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {testimonials.map((t, idx) => (
            <div key={idx} className="p-6 rounded-2xl glass-card border border-slate-800 space-y-4">
              <div className="flex items-center space-x-1 text-amber-400">
                {[...Array(t.rating)].map((_, i) => (
                  <Star key={i} className="w-4 h-4 fill-amber-400" />
                ))}
              </div>
              <p className="text-xs text-slate-300 leading-relaxed italic">"{t.text}"</p>
              <div className="flex items-center space-x-3 pt-2 border-t border-slate-800/60">
                <img src={t.image} alt={t.name} className="w-10 h-10 rounded-full object-cover ring-2 ring-indigo-500/30" />
                <div>
                  <h4 className="text-xs font-bold text-white">{t.name}</h4>
                  <p className="text-[11px] text-slate-400">{t.role}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Configurable Pricing Section */}
      <section className="py-20 border-t border-slate-900 bg-slate-900/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto mb-12 space-y-4">
            <h2 className="text-3xl font-extrabold text-white">Simple, Transparent Pricing</h2>
            <p className="text-slate-400 text-sm">Choose the plan that fits your startup journey.</p>
            
            {/* Billing Toggle */}
            <div className="inline-flex items-center p-1 rounded-xl bg-slate-900 border border-slate-800 text-xs">
              <button
                onClick={() => setBillingCycle('monthly')}
                className={`px-4 py-1.5 rounded-lg font-semibold transition-all ${billingCycle === 'monthly' ? 'bg-indigo-600 text-white' : 'text-slate-400'}`}
              >
                Monthly
              </button>
              <button
                onClick={() => setBillingCycle('annual')}
                className={`px-4 py-1.5 rounded-lg font-semibold transition-all ${billingCycle === 'annual' ? 'bg-indigo-600 text-white' : 'text-slate-400'}`}
              >
                Annual <span className="text-[10px] font-bold text-emerald-300 ml-1">Save 20%</span>
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            
            {/* Free */}
            <div className="p-8 rounded-2xl glass-card border border-slate-800 space-y-6 flex flex-col justify-between">
              <div className="space-y-4">
                <h3 className="text-lg font-bold text-white">Free Plan</h3>
                <div className="flex items-baseline gap-1">
                  <span className="text-4xl font-extrabold text-white font-heading">$0</span>
                  <span className="text-xs text-slate-400">/ forever</span>
                </div>
                <p className="text-xs text-slate-400">Ideal for students and first-time founders exploring early concepts.</p>
                <ul className="space-y-2.5 text-xs text-slate-300 pt-4 border-t border-slate-800">
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> 3 AI Business Idea Validations</li>
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> Basic Score Dial & Verdict</li>
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> 2x2 SWOT Matrix</li>
                  <li className="flex items-center gap-2 text-slate-500 line-through"><CheckCircle2 className="w-4 h-4 text-slate-600" /> PDF Executive Report Export</li>
                </ul>
              </div>
              <button
                onClick={() => openAuthModal('signup')}
                className="w-full py-3 rounded-xl text-xs font-bold bg-slate-900 hover:bg-slate-800 text-white border border-slate-700 transition-colors"
              >
                Get Started Free
              </button>
            </div>

            {/* Pro */}
            <div className="p-8 rounded-2xl glass-card border-2 border-indigo-500 space-y-6 flex flex-col justify-between relative bg-slate-900/90 shadow-xl shadow-indigo-600/10">
              <span className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider bg-indigo-600 text-white shadow">
                MOST POPULAR
              </span>
              <div className="space-y-4">
                <h3 className="text-lg font-bold text-white">Pro Founder</h3>
                <div className="flex items-baseline gap-1">
                  <span className="text-4xl font-extrabold text-white font-heading">
                    {billingCycle === 'monthly' ? '$29' : '$22'}
                  </span>
                  <span className="text-xs text-slate-400">/ month</span>
                </div>
                <p className="text-xs text-slate-400">For active founders requiring full market, financial, and risk intelligence.</p>
                <ul className="space-y-2.5 text-xs text-slate-300 pt-4 border-t border-slate-800">
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> 100 Idea Validations / Month</li>
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> Full TAM/SAM/SOM Market Sizing</li>
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> 5-Year Financial Calculator</li>
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> Unlimited PDF Report Exports</li>
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> 24/7 AI Business Coach Access</li>
                </ul>
              </div>
              <button
                onClick={onStartValidation}
                className="w-full py-3 rounded-xl text-xs font-bold bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg shadow-indigo-600/30 transition-all"
              >
                Start Pro Trial
              </button>
            </div>

            {/* Business */}
            <div className="p-8 rounded-2xl glass-card border border-slate-800 space-y-6 flex flex-col justify-between">
              <div className="space-y-4">
                <h3 className="text-lg font-bold text-white">Business & Team</h3>
                <div className="flex items-baseline gap-1">
                  <span className="text-4xl font-extrabold text-white font-heading">
                    {billingCycle === 'monthly' ? '$99' : '$79'}
                  </span>
                  <span className="text-xs text-slate-400">/ month</span>
                </div>
                <p className="text-xs text-slate-400">For venture studios, accelerators, and startup incubators.</p>
                <ul className="space-y-2.5 text-xs text-slate-300 pt-4 border-t border-slate-800">
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> Unlimited Validations</li>
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> Multi-Idea Side-by-Side Comparison</li>
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> Pitch Deck Slide Generator</li>
                  <li className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /> White-label Shareable Reports</li>
                </ul>
              </div>
              <button
                onClick={() => openAuthModal('signup')}
                className="w-full py-3 rounded-xl text-xs font-bold bg-slate-900 hover:bg-slate-800 text-white border border-slate-700 transition-colors"
              >
                Contact Sales
              </button>
            </div>

          </div>
        </div>
      </section>

      {/* Bottom CTA Banner */}
      <section className="py-16 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="rounded-3xl bg-gradient-to-r from-indigo-900/60 via-indigo-600/40 to-sky-900/60 border border-indigo-500/30 p-8 sm:p-12 text-center space-y-6 relative overflow-hidden shadow-2xl">
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white">Ready to Validate Your Next Business Idea?</h2>
          <p className="text-slate-300 text-sm max-w-xl mx-auto">
            Stop guessing. Get instant data-driven market insights, financial models, and strategic roadmaps in under 60 seconds.
          </p>
          <button
            onClick={onStartValidation}
            className="px-8 py-4 rounded-xl text-base font-bold bg-white text-indigo-900 hover:bg-indigo-50 shadow-xl transition-all hover:scale-105 inline-flex items-center gap-2"
          >
            🚀 Launch IdeaForge AI Engine
          </button>
        </div>
      </section>

    </div>
  );
};
